print("multiplicação de 2 com 3")
print("resultado 6")
print("subtracao 5 com 5")
print("resultado 0")
print("divisao de 10 por 2")
print("resultado = 5")
print("soma de 11 com 6")
print("resultado = 17")
print("raiz quadrada de 4")
print("resultado = 2")
